export const PrivacyPoliciePage = () => {
  return (
    <p
      style={{
        padding: "20px",
        whiteSpace: "break-spaces",
        lineHeight: 1.5,
      }}
    >
      {`
      Política de Privacidad
      Última actualización: Febrero de 2024
      1. INTRODUCCIÓN
      IpH   (la “Empresa”,la “Compañía” o “IpH”) tiene el compromiso de proteger su privacidad y queremos que sepa qué información recolectamos sobre usted y qué hacemos con esa información. La siguiente Política de Privacidad fue creada para ayudarlo a entender cómo será usada la información que usted comparte con la Empresa. Esta Política de Privacidad aplica para toda la información que recolectamos sobre usted.
      Por favor, sepa que nuestros servicios pueden contener hipervínculos a otros sitios de Internet y ocasionalmente estos sitios podrían compartir las marcas de la Empresa  o la marca de uno de nuestros afiliados con políticas de privacidad propias que difieren de las de IpH.
      2. CÓMO CONTACTARNOS
      Si tiene alguna pregunta sobre esta Política de Privacidad, o si quisiera ponerse en contacto con IpH por alguna otra razón, llámenos al número de teléfono que aparece en nuestra página web www.ihingles.com o al email: info@ihingles.com, en caso de ser alumno, envíenos su duda desde la plataforma de aprendizaje, utilizando el enlace “Contáctenos”.
      3. INFORMACIÓN QUE RECOLECTAMOS
      3.1 Información de Registro. No es necesario que usted nos proporcione ningún tipo de información personal para acceder a nuestro sitio web ni para ver la información la cual proveemos generalmente en nuestro sitio web. Sin embargo, podremos ofrecerle la oportunidad de registrarse con nosotros para acceder a un servicio más completo.
      3.1.(a) A pesar de que no es necesario registrarse para acceder a nuestro sitio web, sí es necesario registrarse y crear una cuenta con IpH (IpH Account) para utilizar el Servicio y adquirir nuestros cursos de enseñanza (“Curso”). Cuando usted crea su cuenta con IpH, deberá realizarlo utilizando una cuenta de Google, de la cuál almacenaremos su nombre y su email para así mantenerlo identificado, y brindándole la combinación de nuestras prácticas de seguridad con las de Google.
      3.1.(b) Además, antes de usar el Servicio, puede que se le pida presentar una tarjeta de crédito u otro método de pago, y la dirección adonde le llegan los estados de cuenta de su tarjeta o método de pago. Si Ud. lo autoriza, utilizaremos esta información para facilitar el procesamiento de futuras transacciones mediante un sistema encriptado que cumple con los más altos estándares de seguridad, y todo de conformidad con las regulaciones emitidas por las asociaciones de tarjetas de crédito.
      3.1.(c) Como parte del proceso para crear una cuenta en IpH o participar en ciertas promociones ofrecidas por IpH (tales como rifas, competencias, encuestas, boletines informativos, etc.), además del nombre y dirección de su correo electrónico, puede pedírsele que comparta cierta información concerniente a su educación y preferencias de compra. IpH podría necesitar esta información para conocerlo mejor, ayudarlo a entender nuevos servicios, programas y ofertas en las cuales usted pueda estar interesado, y así mejorar su experiencia online.
      3.1.(d) Cuando Ud. completa el formulario y proporciona sus datos, acepta a que IpH lo contacte en cualquier horario y día de la semana. IpH mantendrá contacto con Ud. para suministrarle información relacionada con el servicio, eventos, publicidad o promociones, de lunes a domingo y días festivos. Las comunicaciones se realizan a través de llamadas telefónicas, vía mensaje de texto (SMS), servicios de mensajería como WhatsApp, Facebook Messenger o correo electrónico, o a través de cualquier medio análogo o digital de comunicación, aquellos medios de contacto serán los que Ud. proporcionó en el momento de la suscripción. En cualquier momento podrá solicitar la exclusión de las listas para el envío de información promocional o publicitaria, por medio del enlace que encuentra para la cancelación de la suscripción, a través del correo electrónico dispuesto en la sección No. 11, de la presente Política de Privacidad, o llamándonos al número de teléfono que aparece en nuestra página web www.openenglish.com.
      3.1.(e) En vista de su interés demostrado al unirse a nuestro directorio telefónico, la Compañía podría invitarle a conversar a través de servicios de mensajería instantánea (“Chat”) tales como WhatsApp, Instagram, Facebook Messenger, u otros servicios similares. Si fuere el caso, Ud. siempre estará en control de su disponibilidad y disposición para mantener un diálogo con nosotros. A estos fines, y antes de iniciar una conversación por Chat, la Compañía le enviará un mensaje vía Chat, y si Ud. contesta afirmativamente, podremos continuar ese Chat para fines promocionales, de atención al cliente y/o soporte técnico. Tenga en cuenta que dependiendo a su ubicación geográfica, dispositivo móvil, o proveedores de servicios de telecomunicaciones, las conversaciones vía Chat podrían verse limitadas o estar restringidas. De igual manera, tenga en cuenta que ni WhatsApp (ni tampoco Instagram, Facebook, Meta y su grupo de empresas relacionadas) patrocinan o auspician nuestro Servicio. Si Ud. tiene alguna pregunta sobre el funcionamiento de su cuenta de mensajería Chat, (ej. WhatsApp), consulte los términos y condiciones en los websites que correspondan.
      3.2 Recolección Automática de Datos. Usted podrá visitar nuestro sitio web y usar algunos de nuestros servicios de manera anónima. Ya se haya registrado o no con nosotros, IpH puede recolectar cierta información personal para el uso de nuestros servicios. Por ejemplo, IpH puede recolectar información concerniente al tipo de navegador de Internet que usted usa, el tipo de computadora o sistema operativo que usted usa, su dirección de IP, la velocidad de su conexión, el nombre del dominio de su proveedor de servicio Internet, la localidad geográfica desde dónde usted está accediendo a nuestros servicios y/o la página web o propaganda desde donde usted se conectó a nuestro sitio web. Cuando Ud. utiliza un dispositivo móvil (como por ejemplo una tableta o un teléfono inteligente) para acceder a nuestro servicio, podríamos acceder, recopilar, y almacenar en su dispositivo y/o guardar de manera remota uno o más “Identificadores de Dispositivos” en su equipo. Estos Identificadores de dispositivos, son pequeños archivos de datos o estructuras lógicas de datos que se asocian o almacenan en su dispositivo móvil para poder identificar de forma única su dispositivo móvil. Una vez que se haya registrado con nosotros, también rastreamos y recolectamos información sobre usted incluyendo sus transacciones con nosotros, nuestros afiliados, u otros, y los patrones que siguió usted al usar nuestro sitio web, como las páginas del sitio que usted visitó, búsquedas que llevó a cabo y el tiempo que usted permaneció en nuestra página. Además, si decide contactarnos, podremos guardar un historial de su correspondencia.
      3.3 Cookies. Cuando usted visita nuestro sitio web o pulsa cualquier hipervínculo que aparece en ella, o usa uno o más de nuestros servicios, podremos usar una tecnología industrial llamada “cookies” la cual almacena cierta información en su computadora y que nos permitirá personalizar su experiencia para alinearla con sus intereses y preferencias, o simplemente facilitar su acceso al usar nuestros servicios. La mayoría de los navegadores permitirán que usted elimine o bloquee las “cookies” de su computador o su disco duro o alertará las mismas cuando estas se activen. Por favor refiérase a las instrucciones de su navegador para ayuda o para conocer mejor sus funciones. Por favor tenga en cuenta, que si usted bloquea de su navegador el uso de estas cookies, el servicio no podrá ser utilizado o no podrá acceder a nuestro sitio web o quizás pueda afectar el funcionamiento de la página como tal. Al permitir la configuración del navegador para aceptar cookies de nuestro sitio web o el Servicio, usted nos autoriza a colocar cookies en su computadora personal y/o dispositivo tecnológico. Sin embargo, los usuarios de nuestro sitio web y Servicio pueden configurar su navegador para aceptar o rechazar todas o ciertas cookies. Tenga en cuenta que, si configura su navegador para deshabilitar las cookies u otras tecnologías, es posible que no pueda acceder a ciertas partes de nuestro sitio web o Servicio, o que otras partes de nuestro Servicio no funcionen correctamente. Para obtener más información acerca de las cookies, haga clic en este enlace: www.aboutcookies.org.
      3.4 Testimonios. IpH puede publicar testimonios de sus clientes en nuestros websites, plataformas y redes sociales (“Website”) así como también en medios publicitarios en televisión (“TV”), los cuales pueden contener información personal. Una vez que Ud. acepta los Términos de Servicio que aplican al Servicio, Ud. otorga su consentimiento a IpH para publicar en su Website y TV cualquier testimonio u opinión que provenga de Ud., así como también sus comentarios, nombre y cualquier otra representación que Ud. nos pudiera enviar por los canales de comunicación que correspondan.
      3.5 Información que Recibimos de Nuestros Afiliados. IpH  también podrá proveer información personal a terceros o páginas de marcas afiliadas a través de las cuales proveemos acceso a nuestros servicios (“Redes Afiliadas”). Cuando se registra con nosotros, la Red Afiliada desde la cual usted accedió podría proveernos con su nombre de usuario y contraseña de dicha red. Algunas de esas Redes Afiliadas u otras redes podrían compartir cualquier otra información que usted comparta, con nosotros. Al usar nuestros servicios, Ud. está de acuerdo con permitirnos recibir y usar cualquier información, excepto información de tarjetas de crédito que usted comparta con las Redes Afiliadas, bajo los mismos términos, como si nos la hubiera compartido con nosotros directamente. Comparta o no una Red Afiliada su información y hasta qué punto lo haga con nosotros, dependerá de su acuerdo con nosotros y la política de privacidad individual o particular de la Red Afiliada.
      4. LO QUE HACEMOS CON SU INFORMACIÓN
      4.1 En general, IpH podrá usar información sobre usted para proporcionar y mejorar el Servicio. IpH podrá compartir esta información con los proveedores del servicio sobre contenido, afiliados y otras entidades de forma no personal para estudios demográficos e información preferencial para los usuarios del servicio, o con otros fines. Esta información podrá incluir el uso y la data demográfica, pero no incluirá información personal.
      4.2 Como parte del Servicio, una vez que Ud. adquiera alguno de nuestros Servicios y proceda a la interacción con instructores, IpH podrá compartir esta información con proveedores de servicio para videoconferencias, exámenes y seminarios web (“Reuniones Online”). Tenga en cuenta que cuando Ud. disfrute de nuestros servicios que incluyan su participación en videoconferencias, , exámenes y seminarios, Ud. estará enviando mensajes a otras personas y organizaciones, incluidos terceros fuera de las Reuniones Online, las cuales podrán ver sus mensajes, contenido, participación en encuestas y cualquier otra información que comparta haciendo uso de su micrófono, cámara, pantalla táctil, teclado y demás atributos de la configuración de su computadora, tablet, teléfono o dispositivo móvil. Además, IpH puede enviarle información acerca de sus avances o de los menores  en los que usted actúa como padre, guardián, tutor o representante legal en el formato de video-mensajes alojados en sitios de Internet de terceros que podrían ser vistos por terceros. Ud. puede pedirnos no enviarlos ni publicarlos en el sitio de ningún tercero.
      4.3 Si usted provee a Inglés para Hispanohablantes con información personal, tomaremos medidas razonables y apropiadas para proteger esta información. Excepto conforme está descrito en esta Política de Privacidad, IpH no revelará, compartirá, venderá ni alquilará información personal recolectada en nuestro sitio web a terceros para uso promocional sin su consentimiento, a menos que sea para un programa específico, para el cual podrá pedirnos no participar. Si Ud. solicita recibir información de nuestros afiliados al seleccionar esta opción en el futuro, podremos compartir su información de registro e información sobre sus transacciones en nuestro servicio con los estudios y/o nuestros afiliados. Si usted accede a nuestros servicios a través de una versión afiliada de nuestro sitio web que contenga un aviso anunciando que esa información será compartida con dicho afiliado, la cual aparecerá bajo el nombre del sitio web afiliado, cualquier información personal o no personal será compartida con dicho sitio web afiliado. Cualquier uso de esa información por parte de IpH estará sujeto a esta Política de Privacidad, y cualquier uso de dicha información por un afiliado estará sujeto a esta Política de Privacidad y la Política de Privacidad del afiliado. En caso que IpH vendiera o transfiriese parte o la totalidad de sus negocios y/o nuestros activos a otra organización, como por ejemplo en una operación de fusión y adquisición, o en el caso de una quiebra, disolución o liquidación, la información personal de nuestros clientes como el nombre y la dirección de correo electrónico y cualquier otra información recolectada a través de nuestro sitio web o servicio, puede ser uno de los elementos del negocio vendidos o transferidos. El comprador resultante, o la sociedad absorbente o adquiriente, cumplirá con los compromisos asumidos en la presente Política de Privacidad. Nosotros no compartimos la información de sus cuentas de tarjetas de crédito con redes afiliadas ni ningún otro tercero, excepto al servicio de procesamiento de tarjetas de crédito descritos más abajo.
      4.4 Para mantenerlo informado sobre nuestros servicios, podríamos enviar correos electrónicos y anuncios que son necesarios para la administración de nuestro sitio web y El Servicio. También podríamos proveer a nuestros usuarios con la opción de unirse a nuestra lista de correos electrónicos para recibir información adicional sobre nuestra página web, servicios y ofertas, incluyendo actualizaciones de nuestra Compañía, o sus afiliados. Adicionalmente, podríamos, en algún momento, permitirle que elija si desea recibir correos de terceros con quienes tenemos relaciones afiliadas. Ud. siempre tendrá la capacidad de cambiar sus opciones accediendo su cuenta de IpH. Cada correo de mercadeo proveniente de IpH incluirá instrucciones de cómo cancelar la suscripción de la lista de correos electrónicos.
      4.5 Trabajamos con terceros quienes proveen servicios, los cuales pueden incluir hospedaje (hosting) de los sitios de Internet, entrega de promociones, procesamiento de órdenes, autorización de tarjetas de crédito, análisis de data, Reuniones Online y otros servicios de naturaleza administrativa. Su información personal, incluyendo información financiera, podrá ser compartida con dichos terceros con el objetivo de proveer a usted con dichos servicios. Hacemos lo posible por imponer obligaciones de confidencialidad en tales proveedores de servicios. También, nuestra Compañía podrá usar su información bajo los términos de esta Política de Privacidad. Además, nos reservamos el derecho de revelar información personal a terceros cuando creamos que es en buena fe y la ley lo requiere, para reforzar nuestros Términos de Servicio, para proteger los derechos, propiedad o seguridad de IpH o el público, para responder a una emergencia, o según haya sido estipulado en esta Política de Privacidad.
      4.6 Después de la terminación o la desactivación de su cuenta, IpH, sus afiliadas, o sus proveedores de servicios podrían conservar la información asociada a la información de su perfil durante un plazo comercialmente razonable con el propósito de realizar copias de seguridad, archivo y/o con fines de auditoría. En base a su petición futura, y según lo requiera la ley aplicable, eliminaremos dichos datos personales o lo dirigiremos a las herramientas correspondientes.
      4.7 Nuestros proveedores de Reuniones Online no divulgan los datos de nuestros estudiantes a terceros, a excepción de: (i) proveedores de servicios que les proporcionan infraestructura técnica; (ii) cuando sea necesario por razones legales o de seguridad; o (iii) a otros afiliados (como por ejemplo Zoom o Voice Communications, Inc.), que proporciona ciertos servicios para habilitar productos y funciones adicionales en nuestros Cursos.
      5. SEGURIDAD
      5.1 Usamos métodos razonables de seguridad para proteger la data que reside en nuestros servidores. Sin embargo, ningún sistema de seguridad es impenetrable; debido a esto, no podemos garantizarle la seguridad absoluta de nuestros servidores. Es también posible que la información que usted nos proporcione pueda ser interceptada durante la transmisión de datos.
      
      5.2 Recuerde salir o cerrar la sesión (sign out, log out) de su curso, y cerrar su navegador cada vez que termine de usar su computador. Esta medida es para asegurarle que otros no puedan tener acceso a su información personal, ya que su computador puede ser accesible a los demás o usado de modo compartido.
      6. HABLA CON NUESTROS MAESTROS
      Durante el término del Servicio, adultos y niños tendrán la oportunidad de interactuar con los asesores académicos (los “Asesores Académicos”) durante las clases en vivo en línea y Reuniones Online, los cuales participarán en sesiones, juegos y actividades a través de un aula virtual y un sistema de chat. Eventualmente, los Asesores Académicos podrían emplear técnicas de moderación durante la sesión en vivo y/o advertir a los usuarios sobre el uso de palabras inapropiadas en su estilo de comunicación. Hacemos un llamado de atención y recomendación a los adultos y los niños bajo su supervisión, que usen las características interactivas de nuestros websites y aplicaciones de nuestras plataformas a que nunca proporcionen información personal sobre ellos, bien a través de ellos mismos o por terceros. Definitivamente, nunca proporcione información para intentar eludir los filtros o restricciones de moderación que podamos tener en nuestros websites y plataformas. También se recomienda que usted como padre o representante legal del niño que supervise cuidadosamente a sus hijos mientras que estos participen en las actividades asociadas con el Servicio.
      7. COPPA Y MENORES
      7.1 Salvo que lo permita la legislación aplicable o que contemos con la autorización previa de alguno de sus padres, guardianes, tutores o representante legal, no recabamos información de menores de 18 años. De conformidad con los requisitos de COPPA, en cualquier sitio o aplicación dirigidos a la infancia, o en cualquier caso en que preguntemos la edad de nuestros usuarios y determinemos que el niño tiene 13 años o menos, tendremos que pedirle el consentimiento a los padres, guardianes, tutores o representantes legales a través de correo electrónico antes de recopilar cualquier información personal por parte del menor.
      7.2 Las personas menores de 18 años, pero mayores de la edad mínima requerida para el consentimiento para usar los servicios en línea donde viven (por ejemplo, 13 en los EE. UU. o 16 en Irlanda), no pueden comprar directamente nuestros productos y/o servicios y establecer crear una cuenta con nuestra Empresa, pero pueden tener uno de sus padres, guardianes, tutores y/o representante legal para hacerlo por ellos y ayudarlos a garantizar que tengan acceso al contenido apropiado. En especial, los Cursos asociados a la marca Inglés para Hispanohablantes Junior, que están dirigidos para niños de edades comprendidas entre los 12 y 14 años de edad. Las personas menores de la edad mínima requerida aplicable para dar un consentimiento válido para usar los servicios en línea no pueden usar nuestros Servicios en línea. Si nos enteramos de que hemos recopilado Datos personales de un menor de esas edades sin consentimiento del padre, tutor, guardián o representante legal, tomaremos las medidas razonables para eliminarlos.
      7.3 Si cree que su hijo está participando en una actividad que recopila información personal y usted como padre, tutor, guardián y/o representante legal no ha recibido un correo electrónico de la Compañía notificando sobre la solicitud de su consentimiento, por favor no dude en ponerse en contacto con nosotros llamando al número de teléfono publicado en nuestro sitio web que corresponda a su país. Cuando necesitemos su consentimiento para estos fines, no le enviaremos información promocional a menos que Ud. así nos haya autorizado, o bien haya participado en una actividad independiente que nos permita poderle enviar información promocional a su correo electrónico.
      7.4 Reconocemos los intereses de privacidad de los niños y alentamos a los padres guardianes, representantes legales y tutores a desempeñar un papel activo en las actividades e intereses en línea de sus hijos. En cualquier momento, los padres pueden revocar el consentimiento que nos permita recopilar más información personal de sus hijos en conexión con una cuenta de usuario o servicios particulares administrados por la Compañía. De igual manera, pueden solicitar que eliminemos de nuestros registros la información personal que hemos recopilado en relación con la cuenta asociada al Curso. Por favor, tenga en cuenta que una solicitud para eliminar registros de datos podría generar como consecuencia la terminación de una cuenta, licencia de uso, u otro servicio administrado por la Compañía.
      7.5 En cualquier notificación a la Compañía, tales como e-mail o correo postal, por favor incluya el nombre de usuario del niño y la dirección de correo electrónico de los padres y número de teléfono. Para proteger la privacidad y la seguridad de los niños, tomaremos las medidas razonables para verificar la identidad de los padres, tutores, guardianes y/o representantes legales antes de conceder el acceso a cualquier información personal.
      8. TERCEROS ANUNCIANTES
      8.1 IpH puede permitir a otras compañías, llamadas servidores de anuncios o redes de anuncios, publicar anuncios desde dentro del Servicio. Estos terceros utilizan tecnología para enviar, directamente a su navegador, los anuncios e hipervínculos que aparecen en el Servicio. En estos casos, ellos reciben de forma automática la dirección IP de usted. Pueden usar además otras tecnologías (como “cookies,” JavaScript, o “faros” de Internet) para medir la efectividad de sus anuncios y para personalizarlos.
      8.2 IpH no proporciona ninguna información personal a estos terceros sin su consentimiento, a menos que sea para un programa específico en el que podrá pedirnos participar. Sin embargo, tenga en cuenta que, si un anunciante pide a IpH publicar un anuncio a un público específico o a un segmento del público, y usted responde a dicho anuncio, el anunciante podría concluir que usted encaja dentro de la descripción del público que quiere alcanzar.
      8.3 Debe consultar las políticas de privacidad de estos terceros. La política de privacidad de IpH no aplica a, ni podemos controlar las actividades de, estos anunciantes terceros u otros sitios en Internet.
      9. ENLACES A OTRAS REDES
      9.1 Los enlaces a otras redes son una parte integral de la funcionalidad de Internet, incluyendo nuestro sitio web. Cualquier hipervínculo que disponga de una URL de un dominio distinto a  ihingles.com o nextu.com en la barra de direcciones de su navegador es un hipervínculo a una página fuera de nuestro servicio. Esto incluye hipervínculos a nuestros proveedores de contenido en el servicio, afiliados, o hipervínculos a terceros que pudieran estar enlazados con IpH. Estas otras redes podrán enviar sus “cookies” a usted, recolectar data o solicitar información personal. IpH no puede garantizar y no se hace responsable por el contenido de otras redes o páginas.
      9.2 Por favor tenga en cuenta que cada vez que Ud. proporcione información personal a otras redes o páginas (por ejemplo, vía mensajes o chat), esa información puede ser recolectada y o usada por personas que usted no conoce. Aunque IpH se esfuerza por proteger a nuestros visitantes, su información personal, y su privacidad, no podemos garantizar la seguridad ni la privacidad de ninguna información que usted revele a otros sitios web, y usted lo hace bajo su propio riesgo. Debe aprender sobre las prácticas y políticas de privacidad y seguridad de sitios externos en Internet antes de entregarles sus datos personales.
      10. NOTA ESPECIAL PARA USUARIOS 
      El Servicio se aloja en servidores localizados en los Estados Unidos de América, y está dirigido primordialmente a usuarios domiciliados en el continente americano. Si usted accede al Servicio desde la Unión Europea (UE), Asia o cualquier otra región con leyes que regulan la colección, el uso o la revelación de información personal distintas a las leyes americanas, tenga en cuenta que está transfiriendo sus datos personales a los Estados Unidos de América, donde las leyes de protección de datos pueden no ser iguales a las de su jurisdicción, y en el acto de proporcionarnos sus datos está consintiendo a:
      uso de sus datos personales con fines legales y para los usos anteriormente identificados de acuerdo a esta Política de Privacidad; y
      la transferencia de sus datos personales a los Estados Unidos de América como se indica arriba.
      Como usuario, usted tiene los siguientes derechos con respecto a su información personal que eventualmente podríamos tener:
      Derecho de acceso y portabilidad. El derecho de obtener acceso y recibir su información personal.
      Derecho a la rectificación. El derecho a obtener la rectificación de su información personal dentro de un período razonable, cuando esa información personal sea inexacta o esté incompleta.
      Derecho a borrado. El derecho a obtener el borrado de su información personal dentro de un período razonable en ciertas circunstancias, en aquellos casos cuando la información personal ya no sea necesaria en relación con los fines para los que fue recopilada o procesada.
      Derecho a oponerse. El derecho a oponerse al procesamiento de su información personal con fines de marketing directo, en la medida en que su oposición esté relacionada con dicho marketing directo.
      Derecho de actualización: Modificar o actualizar sus datos. 
      Independientemente de su ubicación, cualquier pregunta, comentario y solicitud relacionada con nuestra Política de Privacidad es bienvenida, y debe gestionarse a través de nuestro equipo de Atención al Cliente llamando al número de teléfono publicado en nuestro sitio web que corresponda a su país o vía email a: info@openenglish.com.
      11. COMO EXAMINAR, ACTUALIZAR O BORRAR LA INFORMACIÓN DE REGISTRO
      Cuando Ud. visita o se registra en el sitio web acepta recibir circulares promocionales, mensajes o alertas sobre promociones. Ud. podrá ejercer el derecho de opt out, en relación con las comunicaciones comerciales, enviando una solicitud al correo electrónico info@ihingles.com. En la solicitud deberá proporcionar datos auténticos, correctos y actualizados, si realiza la solicitud en representación de un tercero deberá acreditar sus facultades de representación. IpH podrá solicitar información o documentación adicional para verificar su identidad y se reserva el derecho a rechazar la solicitud si no es posible identificarlo. IpH contará con diez (10) días hábiles desde la recepción completa de la solicitud para enviar una respuesta. Tenga en cuenta que Ud. seguirá recibiendo comunicaciones relacionadas con el Servicio contratado y IpH mantendrá ciertos datos personales suyos con la finalidad de resolver disputas, solucionar problemas y dar cumplimiento a lo dispuesto en los Términos del Servicio por el periodo de tiempo determinado por la Ley. 
      11.2 Como parte del uso de nuestros servicios, usted es responsable de actualizar la información sometida para que sea actualizada y esté completa. Para actualizar su información de registro, por favor póngase en contacto con un asesor o representante de la Compañía mediante el número que aparece en nuestra página web o desde su plataforma de aprendizaje, mediante las opciones en el enlace “Contáctanos”.
      11.3 Por favor, tenga en cuenta que al usar nuestros Servicios, usted confirma que está de acuerdo con esta Política de Privacidad, la cual podrá ser enmendada periódicamente. Si usted no está de acuerdo con esta Política de Privacidad, le pedimos por favor que no use nuestros Servicios. Nos reservamos el derecho de hacer cambios a esta Política de Privacidad. Daremos previo aviso a cualquier cambio de este material por cualquier método razonable incluyendo un envío de correo electrónico a su dirección más actualizada dentro del sitio web de IpH o anunciando la noticia y la política enmendada en el sitio web de IpH. El uso continuado por su parte de nuestro sitio web, tras cambios en esta Política de Privacidad significa que usted está de acuerdo y acepta los cambios hechos y que toda la información recolectada o proporcionada después de tal(es) cambio(s) estará gobernada por la Política de Privacidad actualizada.
      11.4 IpH está dedicada a proteger su información personal y agradece cualquier comentario o pregunta sobre esta Política de Privacidad. Si lo desea, puede ponerse en contacto con nuestro equipo llamando al número de teléfono de contacto en nuestra página web correspondiente a su país o, en caso de ser alumno, envíenos su duda desde la plataforma de aprendizaje, utilizando el enlace “Contáctenos”, vía email a: info@ihingles.com o correo físico a: calle 8 # 8 - 36 Chipre, Manizales 170001, CALDAS – COLOMBIA Atención: Administración, Inglés para Hispanohablantes S.A.S.
      12. RETENCIÓN DE INFORMACIÓN
      12.1 Retendremos los datos personales de nuestros usuarios durante el tiempo que sea necesario para participar en los usos descritos en esta Política de Privacidad. Sin embargo, podríamos tener el deber de retener la información durante un periodo adicional cuando la ley aplicable exija un período de retención más largo.
      12.2 Los criterios utilizados para determinar nuestros períodos de retención incluyen los siguientes escenarios: (i) El tiempo que tengamos una relación continua con usted y le proporcionemos Servicios (por ejemplo, mientras tenga una cuenta con nosotros o siga usando disfrutando nuestros Cursos); (ii) Si los propietarios de las cuentas modifican o sus usuarios eliminan información a través de sus cuentas; (iii) Si tenemos la obligación legal de conservar los datos (por ejemplo, ciertas leyes nos exigen que mantengamos registros de sus transacciones durante un cierto período de tiempo antes de que podamos eliminarlos); o (iv) Si la retención es aconsejable a la luz de nuestra posición legal (por ejemplo, con respecto a la ejecución de nuestros acuerdos, la resolución de disputas y los períodos de prescripción exigibles por la ley, litigios o investigaciones administrativas que pudieren ser aplicables).
      12.3 En cualquier caso, durante los periodos de retención que deba aplicar nuestra empresa, tenga la seguridad de que solo usaremos su información de manera lícita, transparente y justa.
      13. INVITACIONES A SUS AMIGOS
      Si decide invitar a sus amigos para que visiten el sitio web de IpH, o para que adquieran nuestros Cursos, participen en concursos y promociones, le pediremos nos suministre el nombre, correo electrónico y país de su amigo, para lo cual debe contar Ud. con el respectivo consentimiento para compartir dicha información. Acto seguido, IpH le enviará a su amigo/a, de forma electrónica, un mensaje invitándolo/a a que visite el sitio web de IpH y/o participe en los concursos o promociones que se pudieran llevar a cabo. Su amigo/a también estará sujeto/a a esta Política de Privacidad y a los Términos de Servicio de la Compañía.
      14. CAMBIOS A ESTA POLÍTICA DE PRIVACIDAD
      Podremos actualizar los avisos asociados a nuestra Política de Privacidad periódicamente. Para tener en cuenta los cambios en la manera en que recopilamos y/o procesamos datos personales por favor visite esta sección frecuentemente. Siempre publicamos la fecha de “Última actualización” en la parte superior. Si tuviéramos la necesidad de realizar cambios sustanciales y/o exhaustivos a esta Política de Privacidad, se lo notificaremos y le brindaremos la oportunidad de revisarla antes de que elija continuar usando nuestros Servicios.
      `}
    </p>
  );
};
